version: "3.9"

services:
  server:
    image: brianjleeofcl/nufb-uniforms-server
    volumes: [cert:/api/cert]
    ports:
      - 80:80
      - 443:443
    env_file:
      - ${DB_ENV}
      - ${API_ENV}
  db:
    image: postgres:14-alpine
    volumes: [database:/var/lib/postgresql/data]
    env_file:
      - ${DB_ENV}
    ports:
      - 5432:5432

volumes:
  database:
  cert:
