FROM golang:1.17.2 AS build
WORKDIR /build
COPY . .
RUN CGO_ENABLED=0 go build -o /build/

FROM alpine:latest
WORKDIR /api
COPY --from=build /build/nufb-uniform-tracker ./
COPY --from=brianjleeofcl/nufb-uniforms-frontend:latest /build/ ./frontend/
EXPOSE ${PORT}
CMD ["/api/nufb-uniform-tracker"]
